<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $users = Data::get('user')?>
<?php ErrMgr::attach($users) ?>


	<!-- container -->
	<div class="container">

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">Novo Utilizador</h1>
				</header>
				
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<hr>
							<form method="post" action="<?=Url::toRoute('user/store')?>">
								<div class="top-margin">
									<label>Name <span class="text-danger">*</span></label>
									<input type="text" value="<?=$users->name?>" name="name" class="form-control" placeholder="Insira o seu Nome" required>
                                    <?= ErrMgr::bind('name') ?>
								</div>
								<div class="top-margin">
									<label>Username <span class="text-danger">*</span></label>
									<input type="text" value="<?=$users->username?>" name="username" class="form-control" placeholder="Insira o seu Username" required>
                                    <?= ErrMgr::bind('username') ?>
								</div>
								<div class="top-margin">
									<label>Password <span class="text-danger">*</span></label>
									<input type="password" value="<?=$users->password?>" name="password" class="form-control" placeholder="Insira a sua Password" required>
                                    <?= ErrMgr::bind('password') ?>
								</div>
								<div class="top-margin">
									<label>Email <span class="text-danger">*</span></label>
									<input type="email" value="<?=$users->email?>" name="email" class="form-control" placeholder="Insira o seu Email" required>
                                    <?= ErrMgr::bind('email') ?>
								</div>
								<div class="top-margin">
									<label>Data de Nascimento <span class="text-danger">*</span></label>
									<input type="date" value="<?=$users->email?>" name="datanasc" class="form-control" placeholder="Insira a sua Data de Nascimento" required>
                                    <?= ErrMgr::bind('datanasc') ?>
                                </div>

								<hr>

									<div class="col-lg-4 text-right">
										<button class="btn btn-action" type="submit">New</button>
									</div>
								</div>
							</form>
						</div>
					</div>

				</div>
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>