<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $users = Data::get('user') ?>
<?php ErrMgr::attach($users) ?>

	<!-- container -->
	<div class="container">

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">Edit User</h1>
				</header>
				

					<div class="panel panel-default">
						<div class="panel-body">

                            <hr>


							<form class="form-horizontal" method="post" action="<?=Url::toRoute('book/update', $users->id)?>">

                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="name">Name:<span class="text-danger">*</span></label>
                                    <div class="col-sm-6">
										<input type="text" value="<?=$users->name?>" name="name" class="form-control" placeholder="Enter bo	ok name" required>
                                  		<?= ErrMgr::bind('name') ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="name">Username:<span class="text-danger">*</span></label>
                                    <div class="col-sm-6">
										<input type="text" value="<?=$users->username?>" name="username" class="form-control" placeholder="Enter Username" required>
                                    	<?= ErrMgr::bind('username') ?>
                                    </div>
								</div>
								<div class="form-group">
                                    <label class="control-label col-sm-2" for="name">Password:<span class="text-danger">*</span></label>
                                    <div class="col-sm-6">
										<input type="password" value="<?=$users->password?>" name="password" class="form-control" placeholder="Enter Password" required>
                                    	<?= ErrMgr::bind('password') ?>
                                    </div>
								</div>
								<div class="form-group">
                                    <label class="control-label col-sm-2" for="name">Email:<span class="text-danger">*</span></label>
                                    <div class="col-sm-6">
										<input type="email" value="<?=$users->email?>" name="email" class="form-control" placeholder="Enter Email" required>
                                   		<?= ErrMgr::bind('email') ?>>
                                    </div>
								</div>
								<div class="form-group">
                                    <label class="control-label col-sm-2" for="name">Data de Nascimento:<span class="text-danger">*</span></label>
                                    <div class="col-sm-6">
										<input type="date" value="<?=$users->email?>" name="datanasc" class="form-control" placeholder="Enter Data de Nascimento" required>
                                    	<?= ErrMgr::bind('datanasc') ?>
                                    </div>
                                </div>


								<hr>

									<div class="col-lg-4 text-right">
										<button class="btn btn-default" type="submit">Save</button>
									</div>
								</div>
							</form>
						</div>
					</div>


				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>