<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $users = Data::get('user') ?>

    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">User Index</li>
        </ol>

        <h2 class="text-left top-space">User Index</h2>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped"><thead><th><h3>Id</h3></th><th><h3>Nome</h3></th><th><h3>Username</h3></th><th><h3>Password</h3></th><th><h3>Is Admin</h3></th><th><h3>Blocked</h3></th><th><h3>Score</h3></th><th><h3>Email</h3></th><th><h3>Data de Nascimento</h3></th></thead>
                <tbody>
                <?php foreach ($users as $user) { ?>
                    <tr>
                    <td><?=$user->id?></td>
                    <td><?=$user->nome?></td>
                    <td><?=$user->username?></td>
                    <td><?=$user->password?></td>
                    <td><?=$user->isadmin?></td>
                    <td><?=$user->blockers?></td>
                    <td><?=$user->score?></td>
                    <td><?=$user->email?></td>
                    <?php
                    $date = $user->datanasc;
                    //$result = $date->format('Y-m-d');
                    ?>
                    <td><?=$user->datanasc?></td>

                    <td>
                        <a href="<?=Url::toRoute('user/show', $user->id)?>" class="btn btn-info" role="button">Show</a>
                        <a href="<?=Url::toRoute('user/edit', $user->id)?>" class="btn btn-info" role="button">Edit</a>
                        <a href="<?=Url::toRoute('user/destroy', $user->id)?>" class="btn btn-warning" role="button">Delete</a>
                    </td>
                    </tr>
                <?php } ?>

                </tbody>

            </table>

            </div>
        </div> <!-- /row -->

    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>