<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $users = Data::get('user') ?>

	<!-- container -->
	<div class="container">

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">View Book</h1>
				</header>
				
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<hr>
							
							<form method="post" action="<?=Url::toRoute('user/index')?>">
								<div class="top-margin">
									<label>Nome <span class="text-danger">*</span></label>
									<input readonly="true" type="text" value="<?=$users->nome?>" name="nome" class="form-control">
								</div>
								<div class="top-margin">
									<label>Username <span class="text-danger">*</span></label>
									<input readonly="true" type="text" value="<?=$users->username?>" name="username" class="form-control">
								</div>
								<div class="top-margin">
									<label>Password <span class="text-danger">*</span></label>
									<input readonly="true" type="text" value="<?=$users->password?>" name="password" class="form-control">
								</div>
								<div class="top-margin">
									<label>Email <span class="text-danger">*</span></label>
									<input readonly="true" type="text" value="<?=$users->email?>" name="email" class="form-control">
								</div>
								<div class="top-margin">
									<label>Data de Nascimento <span class="text-danger">*</span></label>
									<input readonly="true" type="text" value="<?=$users->datanasc?>" name="datanasc" class="form-control">
                                </div>

								<hr>

									<div class="col-lg-4 text-right">
										<button class="btn btn-action" type="submit">Return</button>
									</div>
								</div>
							</form>
						</div>
					</div>

				</div>
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>