<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="GET" action="">
        Nome: <input type="text" name="nome"><br>
        Despesas: <input type="text" name="despasas"><br>
        Credito: <input type="text" name="credito"><br>
        NumPrestacoes: <input type="text" name="nprest"><br>
        <input type="submit">
    </form>
    <?php Layout::includeLayout('indexheader'); ?> <!-- para o header da página principal -->

    <?php Layout::includeLayout('footer')?> <!-- para o footer -->
</body>
</html>