<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\Data;
Layout::includeLayout('indexheader');
$variavel = Session::get('buscarCartasAoDeck'); 
$gameengine = Session::get('game');
echo $gameengine->getBotCardCount();
?>

<div>
<br><br><br><br>
<h1 align = "center">GO Fish game<h1>

<?php 
    $botcards = $gameengine->getBotHand();

    echo '<h3 align="center"> Pontos Bot : ' . $gameengine->getPointBot() . ' </h3>';

    echo '<table align = "center">';
    /*
    for ($i = 1; $i <= $botcards; $i++)
    {
        echo '<td>';
        echo '<img src=" '.Asset::image('back.png') . '"  height = 50%, width = 50%>';
        echo '</td>';
    }
    */

    foreach ($botcards as $card)
    {
        echo '<td>';
        //echo '<a href="'. Url::toRoute('game/askcard', $card->getIdentifier()) .'?card_player">';
        echo '<img src= "' . Asset::image($card->getIdentifier() . '.png') . '" height = 50%, width = 50%>';
        //echo '</a>';
        echo '</td>';
    }
    
    echo '</table align = "center">';

    echo '<h2 align = "center"> Baralho </h2>';

    echo '<table align = "center">';
    
    if($gameengine->countCardsInDeck() > 0)
    {
        echo '<td>';
        if(Session::get('buscarCartasAoDeck') == true)
        {
            echo '<a href="' . URL::toRoute('game/goFish') . '">';
            echo '<img src=" '.Asset::image('back.png') . '" height = 50%, width = 50%>';
            echo '</a>';   
        }
        else
        {
            echo '<img src=" '.Asset::image('back.png') . '" height = 50%, width = 50%>';
        }
        echo '</td>';
    }
    
    echo '</table>';
    echo '<h2 align = "center"> Cartas do Jogador </h2>';

    echo '<h3 align="center"> Pontos Jogador : ' . $gameengine->getPointPlayer() . ' </h3>';

?>

<?php
    $playerHand = $gameengine->getPlayerHand();
    echo '<table align = "center">';
    
    foreach ($playerHand as $card)
    {
        echo '<td>';
        if(Session::get('buscarCartasAoDeck') == false)
        {
            echo '<a href="'. Url::toRoute('game/askcard', $card->getIdentifier()) .'">';
            echo '<img src= "' . Asset::image($card->getIdentifier() . '.png') . '" height = 50%, width = 50%>';
            echo '</a>';    
        }
        else
        {
            echo '<img src= "' . Asset::image($card->getIdentifier() . '.png') . '" height = 50%, width = 50%>';
        }
        echo '</td>';
    }
     echo '</table>';
?>

    <div align="right">
        <button onclick="">Go Fish</button>
    </div>

<?php
    if($gameengine->showturn() == true)
    {
        //Jogador
        /*
        $cartamandada = Data::get('cartapedida');
        if($cartamandada!= 11 && $cartamandada != 12 && $cartamandada != 13 && $cartamandada != 14)
        {
            $cartapedir = $cartamandada;
        }
        else if($cartamandada == 11)
        {
            $cartapedir = "J";
        }
        else if($cartamandada == 12)
        {
            $cartapedir = "Q";
        }
        else if($cartamandada == 13)
        {
            $cartapedir = "K";
        }
        else if($cartamandada == 14)
        {
            $cartapedir = "A";
        }
        */
    }
    else
    {
        //Bot
        /*
        $cartamandada = Data::get('cartapedidabot');
        if($cartamandada!= 11 && $cartamandada != 12 && $cartamandada != 13 && $cartamandada != 14)
        {
            $cartapedir = $cartamandada;
        }
        else if($cartamandada == 11)
        {
            $cartapedir = "J";
        }
        else if($cartamandada == 12)
        {
            $cartapedir = "Q";
        }
        else if($cartamandada == 13)
        {
            $cartapedir = "K";
        }
        else if($cartamandada == 14)
        {
            $cartapedir = "A";
        }
        */
    }
    //$gameengine->askForCard($cartamandada);
?>

    <div style="background-color:#f44336; color:white; padding: 20px;">
        <?php
            if($gameengine->showturn() == false)
            {
                echo '<h5 align="center" >';
                //echo 'O Bot pediu'. $cartapedir .'';
                echo '</h5>';
            }
            else
            {
                echo '<h5 align="center" >';
                //echo 'Você pediu '. $cartapedir . '';
                echo '</h5>';
            }
        ?>
    </div>

</div>

<?php Layout::includeLayout('footer')?>