<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
Layout::includeLayout('indexheader'); 
$gameEngine = Data::get('game');
?>

<div>
<br><br><br>
<h1>GO fish game<h1>

<?php 
    $botcards = $gameEngine->getBotCardCount();

    echo '<table>';
    for ($i = 1; $i <= $botcards; $i++){
        echo '<td>';
        echo '<img src=" '.Asset::image('back.png') . '">';
        echo '</td>';
    }
    echo '</table>';



    echo '<h1> Baralho </h1>';
    //Tracy\Debugger::barDump($gameEngine->countCardsInDeck(), 'cartas no deck');
    
    
   if($gameEngine->countCardsInDeck() > 0)
    {
       echo '<img src=" '.Asset::image('back.png') . '">';
    }
    
?>

    echo '<h1> Cartas do Jogador </h1>'

    <?php
        $playerHand = $gameEngine->getPlayerHand();
        echo '<table>';
        foreach ($playerHand as $card)
        {
            echo '<td>';
            echo '<img src= "' . Asset::image($card->getIdentifier() . '.png') . '">';
            echo '</td>';
        }
        echo '</table>';
    ?>

</div>

<?php Layout::includeLayout('footer')?>