<?php use ArmoredCore\WebObjects\Layout;

Layout::includeLayout('header') ?>

	<!-- container -->
	<div class="container">

		<ol class="breadcrumb">
			<li><a href="index.html">Home</a></li>
			<li class="active">User access</li>
		</ol>

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">Registar</h1>
				</header>
				
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3 class="thin text-center">Registe-se!</h3>
							<p class="text-center text-muted">Crie uma conta para poder jogar ao grandioso Go Fish aka Jogo do Peixinho!</p>
							<hr>
							
							<form id="login-form" class="form" action="" method="POST">
							<div class="form-group">
                                <label for="username" class="text-info">Nome:</label><br>
                                <input type="text" name="nome" id="nome" require="required" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="data" class="text-info">Data de Nascimento:</label><br>
                                <input type="date" name="data" id="data" require="required" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="username" class="text-info">Username:</label><br>
                                <input type="text" name="username" id="username" require="required" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="password" class="text-info">Password:</label><br>
                                <input type="password" name="password" id="password" require="required" class="form-control">
                            </div>

								<hr>

								<div class="row">
									<div class="col-lg-8">
										<!--<b><a href="">Esqueceste-te da password?</a></b>-->
									</div>
									<div class="col-lg-4 text-right">
										<button class="btn btn-action" type="submit">Registar</button>
									</div>
								</div>
							</form>
						</div>
					</div>

				</div>
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>